const GET_SELLER = "GET_SELLER"
const SHOW_DETAIL = "SHOW_DETAIL"
const GET_GOODS = "GET_GOODS"
const SHOW_FOOD ="SHOW_FOOD"
const ONLY_CONTENT ="ONLY_CONTENT"
const SHOW_RATING ="SHOW_RATING"
const SELECT_TYPE ="SELECT_TYPE"
const GET_RATINGS ="GET_RATINGS"
const BTNTEXT_CHANGE="BTNTEXT_CHANGE"

export default {
	GET_SELLER,
	SHOW_DETAIL,
	GET_GOODS,
	SHOW_FOOD,
	ONLY_CONTENT,
	SHOW_RATING,
	SELECT_TYPE,
	GET_RATINGS,
	BTNTEXT_CHANGE
}